stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Building the application"

test-job:
  stage: test
  script:
    - echo "Testing the application"

deploy-job:
  stage: deploy
  script:
    - echo "Deploying the application"   
